### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by ShamilSE** [Kirabin/ft_change_settings#1]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/54128722/116233980-ad3daa80-a764-11eb-8afc-6916fc2ce6bf.png">

**Comment by kirabin** [comment]
Please, leave steps on how you got this warning message.

**Comment by ShamilSE** [comment]
when I log in into my school account

**Comment by kirabin** [comment]
You added action "Bless NetBoot Image Folder" by yourself. Deleting it solved the problem.
